name: keyboard_crash
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cached_network_image: ^3.1.0
  flutter_keyboard_visibility: ^5.0.3
  intl: ^0.17.0
  provider: ^6.0.0
  uuid: ^3.0.4
  logging: ^1.0.2
  logging_appenders: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.2
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
